// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJyllFZlhCMbi2-abv-Kp2wZjzz6jCH4',
    appId: '1:450136340946:web:0d4e68668e6fc79c6d300b',
    messagingSenderId: '450136340946',
    projectId: 'totalxtest-b4886',
    authDomain: 'totalxtest-b4886.firebaseapp.com',
    storageBucket: 'totalxtest-b4886.firebasestorage.app',
    measurementId: 'G-R109X9Q54X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3jXLNIqARyavAjQ1cp2XC-82A4mTax_4',
    appId: '1:450136340946:android:de9a32350de67d486d300b',
    messagingSenderId: '450136340946',
    projectId: 'totalxtest-b4886',
    storageBucket: 'totalxtest-b4886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5xHsV88GqEdxLQvjXlKaJSaNj2FUQK7c',
    appId: '1:450136340946:ios:2e88b4cb166e3fa56d300b',
    messagingSenderId: '450136340946',
    projectId: 'totalxtest-b4886',
    storageBucket: 'totalxtest-b4886.firebasestorage.app',
    iosBundleId: 'com.example.totalxtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5xHsV88GqEdxLQvjXlKaJSaNj2FUQK7c',
    appId: '1:450136340946:ios:2e88b4cb166e3fa56d300b',
    messagingSenderId: '450136340946',
    projectId: 'totalxtest-b4886',
    storageBucket: 'totalxtest-b4886.firebasestorage.app',
    iosBundleId: 'com.example.totalxtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUJyllFZlhCMbi2-abv-Kp2wZjzz6jCH4',
    appId: '1:450136340946:web:64aeddce44d5419c6d300b',
    messagingSenderId: '450136340946',
    projectId: 'totalxtest-b4886',
    authDomain: 'totalxtest-b4886.firebaseapp.com',
    storageBucket: 'totalxtest-b4886.firebasestorage.app',
    measurementId: 'G-RZVZB3M45Q',
  );
}
